Pin cryptography to 3.3.2
The latest version of module breaks compatibility with the
latest version of pip.

Error:

 Traceback (most recent call last):
   File "<string>", line 1, in <module>
   File "/tmp/pip-build-vqk6fya9/cryptography/setup.py", line 14, i
   in <module> from setuptools_rust import RustExtension
 ModuleNotFoundError: No module named 'setuptools_rust'

Issue-Id: IT-21538 IT-21509
Change-Id: I83db995ae8321377b861cabcf6ac53485778e471
Signed-off-by: Anil Belur <abelur@linuxfoundation.org>