Fix: JaCoCo exclude patterns format
Fix JaCoCo exclude patterns format. JJB 6.x does
not process the job config when double quotes are used and returns
the following error.

Error:
requests.exceptions.HTTPError: 500 Server Error: Server Error for url:
https://jenkins.opendaylight.org/releng/job/distribution-
merge-managed-argon/config.xml

Issue: RELENG-5118
Change-Id: Id8b2c02c7feb1e5f2ed443eb59dd61e040a31d1c
Signed-off-by: Anil Belur <abelur@linuxfoundation.org>