Update patch set 1
Patch Set 1:

what is causing tox to fail ?

FileExistsError: [Errno 17] File exists: '/home/abelur/git/global-jjb/.tox/coala/bin'
ERROR: InvocationError: '/home/abelur/git/global-jjb/.tox/coala/bin/nodeenv -p'

Patch-set: 1
Label: Code-Review=0