Fix: Workaround for yaml multiline string
Fix JaCoCo exclude patterns format. JJB 6.x does not process
the job config when double quotes are used and returns the
following error.

Error:
requests.exceptions.HTTPError: 500 Server Error: Server Error for url:
https://jenkins.opendaylight.org/releng/job/distribution-\
merge-managed-argon/config.xml

Using YAML multiline '>-' introduces spaces between lines that causes
JJB updates to fail when the job exists on Jenkins. Therefore as
workaround use double-quoted string with newline escape.

Using '>-' introduces space that causes consecutive JJB updates
to fail with the same 500 internal error.

Expected pattern:
"**/gen/**,**/generated-sources/**,**/yang-gen**,**/pax/**"

Generated by JJB with YAML multiline '>-':
"**/gen/**, **/generated-sources/**, **/yang-gen**, **/pax/**"

Therefore use the workaround of double quoted string with
newline escape.

Issue: RELENG-5118
Change-Id: Id26a78280768dbc43a74d3d393907da946c15dd4
Signed-off-by: Anil Belur <abelur@linuxfoundation.org>