Revert "remove --user now that pip is 20.0.x"
This reverts commit 8a2651316c6c2f121a32d1121dd3ff7dc0e8ac24.
Invoking python3 -m pip without --user yields this error:

PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.6'

Change-Id: I97e70b17cbc524f18ef4f37f7a4e5ad0afec4812
Signed-off-by: Lott, Christopher (cl778h) <cl778h@att.com>