Update patch set 1
Patch Set 1:

> Patch Set 1: Code-Review-1
> 
> Tested locally with poor results:
> 
> Traceback (most recent call last):
>   File "/Users/clott/Programs/venv-py37/lib/python3.7/site-packages/jenkins_jobs/formatter.py", line 38, in deep_format
>     ret = CustomFormatter(allow_empty).format(obj, **paramdict)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/string.py", line 186, in format
>     return self.vformat(format_string, args, kwargs)
>   File "/Users/clott/Programs/venv-py37/lib/python3.7/site-packages/jenkins_jobs/formatter.py", line 135, in vformat
>     return Formatter.vformat(self, format_string, args, kwargs)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/string.py", line 190, in vformat
>     result, _ = self._vformat(format_string, args, kwargs, used_args, 2)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/string.py", line 230, in _vformat
>     obj, arg_used = self.get_field(field_name, args, kwargs)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/string.py", line 295, in get_field
>     obj = self.get_value(first, args, kwargs)
>   File "/Users/clott/Programs/venv-py37/lib/python3.7/site-packages/jenkins_jobs/formatter.py", line 139, in get_value
>     return Formatter.get_value(self, key, args, kwargs)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/string.py", line 252, in get_value
>     return kwargs[key]
> KeyError: 'mvn-settings'

yeah, its required in multiple places, and also complicated by the legacy sonar-cube job which is being phased out, but it still used in some places. digging further

Patch-set: 1