Pin importlib-resources version to <2.0.0
The current virtualenv 20.0.21 is incompatible with importlib-resources
2.0.0. This patch pins the version of importlib-resources temporarily
until a virtualenv version that supports it is released. This resolves
the ignored error in tox-verify job builds:

    ERROR: virtualenv 20.0.21 has requirement
    importlib-resources<2,>=1.0; python_version < "3.7", but you'll
    have importlib-resources 2.0.0 which is incompatible.

Issue: RELENG-2993
Signed-off-by: Thanh Ha <zxiiro@gmail.com>
Change-Id: I04cf74f4209104475c1548653f157821814970df