Pin python-cinderclient to 4.3.0.
A new version of python-cinderclient 5.0.0 is released which breaks
the openstack jobs.

ImportError: No module named v1.contrib

Issue: IT-17567
Change-Id: I2736c464ff82a3b08433031a5e924e1345c2c317
Signed-off-by: Anil Belur <abelur@linuxfoundation.org>